spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: devPathRoute
      port: 27017
      host: localhost

application:
  data:
    disable: false
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days